# -*- coding: utf-8 -*-
"""dasboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otYG9_oBiS_ObTDXZ3SxkZtcEd1NIZXM
"""


import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Judul aplikasi
st.title("Analisis Data Kualitas Udara di Kota Wanshouxigong")

# 1. Memuat Dataset dari Google Drive
@st.cache_data
def load_data():
    data = pd.read_csv('Dashboard/all_data.csv')
    return data

data = load_data()


# Korelasi antara WSPM dan RAIN
st.subheader("Korelasi antara Kecepatan Angin dengan Hujan")
correlation_wspm_rain = data[['WSPM', 'RAIN']].corr(method='pearson')


# Visualisasi scatter plot WSPM vs RAIN
plt.figure(figsize=(8, 6))
sns.scatterplot(x=data['WSPM'], y=data['RAIN'])
plt.title('Korelasi antara kecepatan angin dan hujan')
plt.xlabel('Kecepatan Angin (WSPM)')
plt.ylabel('Hujan (RAIN)')
st.pyplot(plt)
plt.close()

# Pengaruh DEWP terhadap TEMP
st.subheader("Pengaruh Kelembaban Udara terhadap Suhu Udara")
correlation_dewp_temp = data[['DEWP', 'TEMP']].corr(method='pearson')

# Visualisasi scatter plot DEWP vs TEMP
plt.figure(figsize=(8, 6))
sns.scatterplot(x=data['DEWP'], y=data['TEMP'])
plt.title('Pengaruh kelembaban terhadap suhu udara')
plt.xlabel('kelembaban udara (DEWP)')
plt.ylabel('Suhu (TEMP)')
st.pyplot(plt)
plt.close()
